<?php

namespace Smart\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CatgeorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatgeorieRepository extends EntityRepository
{
}
