<?php

namespace Smart\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GovernoratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GovernoratRepository extends EntityRepository
{
}
