<?php

namespace Smart\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getUserByRole($role, $nombreParPage, $page) {
		if ($page < 1) {
	throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
	}
    $qb = $this->_em->createQueryBuilder();
    $qb->select('u')
            ->from($this->_entityName, 'u')
			->leftJoin('u.image', 'i')
			->addSelect('i')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"' . $role . '"%')
			->getQuery();
			
			
	$qb->setFirstResult(($page-1) * $nombreParPage)->setMaxResults($nombreParPage);
	
	return new Paginator($qb);
    
}
}
