parameters:
#    pfe_user.example.class: PFE\UserBundle\Example

services:
  smart_userbundle_registration.registration.form.type:
        class: Smart\UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            -
                name: form.type
                alias: smart_userbundle_registration
  